### ISSUE TITLE
python2 run_sate.py  error

### ISSUE THREAD

**Issue by 1457634627** [sate-dev/sate-core#40]
Traceback (most recent call last):
  File "run_sate.py", line 27, in <module>
    from sate.mainsate import sate_main
  File "/www/tools/satesrc-v2.2.7-2013Feb15/sate-core/sate/mainsate.py", line 37, in <module>
    from sate.satejob import *
  File "/www/tools/satesrc-v2.2.7-2013Feb15/sate-core/sate/satejob.py", line 34, in <module>
    from sate.treeholder import TreeHolder, resolve_polytomies
  File "/www/tools/satesrc-v2.2.7-2013Feb15/sate-core/sate/treeholder.py", line 26, in <module>
    from sate.tree import PhylogeneticTree
  File "/www/tools/satesrc-v2.2.7-2013Feb15/sate-core/sate/tree.py", line 25, in <module>
    from dendropy import convert_node_to_root_polytomy
ImportError: cannot import name convert_node_to_root_polytomy

How to solve this problem

**Comment by mtholder** [comment]
Hi, I think that this issue arises from dependency on old behavior in the DendroPy package. Possible solutions would include installing an old version of DendroPy or the suggestions in this issue: https://github.com/smirarab/sepp/issues/13

I hope that helps,
Mark
